### ISSUE TITLE
I can't activate my xt mapper on my cell phone

### ISSUE THREAD

**Issue by trembo13** [Xtr126/XtMapper#63]
When I run the command in adb these codes appear
C:\Users\User>adb shell sh /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh
java.lang.SecurityException:
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2438)
        at android.os.Parcel.createException(Parcel.java:2422)
        at android.os.Parcel.readException(Parcel.java:2405)
        at android.os.Parcel.readException(Parcel.java:2347)
        at android.os.IServiceManager$Stub$Proxy.addService(IServiceManager.java:452)
        at android.os.ServiceManagerProxy.addService(ServiceManagerNative.java:72)
        at android.os.ServiceManager.addService(ServiceManager.java:249)
        at android.os.ServiceManager.addService(ServiceManager.java:218)
        at xtr.keymapper.server.RemoteService.<init>(RemoteService.java:36)
        at xtr.keymapper.server.RemoteService.main(RemoteService.java:28)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:378)

and the app does not activate,I've also tried to put the code that the app itself gives and it didn't work either

I thought I would just paste the code and the app would activate

**Screenshots**
![image](https://github.com/Xtr126/XtMapper/assets/153560915/eec20a11-2211-46b8-8d41-ef6a0f1643e3)

**Device 
- samsung galaxy s10 plus exynos
 - one ui 4.1
 - Android version 12

**Comment by Xtr126** [comment]
This happens on non rooted devices, unfortunately I haven’t found a fix to it currently but I assume it will work fine when Shizuku support is implemented.

**Comment by Xtr126** [comment]
Well it turns out SELinux is the issue, not root.

**Comment by Tunna75** [comment]
Same problem but with a Samsung S10 5g Exynos

**Comment by Xtr126** [comment]
Fixed in v2.1.2 https://github.com/Xtr126/XtMapper/releases/tag/v2.1.2
