### ISSUE TITLE
Waydroid support

### ISSUE THREAD

**Issue by enderprism** [Xtr126/XtMapper#9]
Hi, this app is amazing, but I can't seem to run it in Waydroid.
When I try to run xtMapper.sh, nothing happens. And when I try to run the overlay, it times out since it isn't activated.
Here's the logcat output:
```logcat
03-07 22:45:27.174  5550  5550 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
03-07 22:45:27.175  5550  5550 I AndroidRuntime: Using default boot image
03-07 22:45:27.175  5550  5550 I AndroidRuntime: Leaving lock profiling enabled
03-07 22:45:27.176  5550  5550 E app_process: Could not open boot oat file for extracting boot class path: File /apex/com.android.art/javalib/boot.art:/system/framework/boot-framework.art!/system/etc/x86_64/boot-image.vdex does not exist.
03-07 22:45:27.176  5550  5550 E AndroidRuntime: JNI_CreateJavaVM failed
```

**Comment by enderprism** [comment]
My current version is 1.3 from IzzyOnDroid. I will try updating to 1.4 to see if it changes anything.

**Comment by enderprism** [comment]
The activation still fails with the same error code.
(I am doing the ADB activation).

**Comment by Xtr126** [comment]
This seems to be an issue with waydroid and not the app itself. You can try this workaround
Try setting boot class path before activation as a workaround: 
```
export BOOTCLASSPATH=/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/core-icu4j.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/framework-atb-backward-compatibility.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar:/apex/com.android.mediaprovider/javalib/framework-mediaprovider.jar:/apex/com.android.os.statsd/javalib/framework-statsd.jar:/apex/com.android.permission/javalib/framework-permission.jar:/apex/com.android.sdkext/javalib/framework-sdkextensions.jar:/apex/com.android.wifi/javalib/framework-wifi.jar:/apex/com.android.tethering/javalib/framework-tethering.jar
```
Then to activate use this command:
`env LD_LIBRARY_PATH=$(echo /data/app/*/xtr.keymapper*/lib/x86_64) CLASSPATH=$(echo /data/app/*/xtr.keymapper*/base.apk) /system/bin/app_process /system/bin xtr.keymapper.server.InputService`  
waydroid runs Android in a container, it doesn't have direct access to input devices (evdev). You might need to hotplug input devices (kbd,mouse) for the keymapper to function. I couldn't find any way to get exclusive access to mouse input devices from within Android other than reading from kernel evdev devices.

**Comment by YogSottot** [comment]
Tried this, but:
```
03-26 15:44:24.604  2805  2805 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
03-26 15:44:24.605  2805  2805 I AndroidRuntime: Using default boot image
03-26 15:44:24.605  2805  2805 I AndroidRuntime: Leaving lock profiling enabled
03-26 15:44:24.606  2805  2805 I app_process: Core platform API reporting enabled, enforcing=false
03-26 15:44:24.638  2805  2805 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
03-26 15:44:24.638  2805  2805 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt66l.dat
03-26 15:44:24.639  2805  2805 W app_process: Unexpected CPU variant for X86 using defaults: x86_64
03-26 15:44:24.645  2805  2805 W app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
03-26 15:44:24.647  2805  2805 D AndroidRuntime: Calling main entry xtr.keymapper.server.InputService
03-26 15:44:24.648  2805  2805 E AndroidRuntime: ERROR: could not find method xtr.keymapper.server.InputService.main(String[])
03-26 15:44:24.648  2805  2805 D AndroidRuntime: Shutting down VM
03-26 15:44:24.648  2805  2805 E AndroidRuntime: FATAL EXCEPTION: main
03-26 15:44:24.648  2805  2805 E AndroidRuntime: PID: 2805
03-26 15:44:24.648  2805  2805 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmouse_read.so" not found
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1664)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at xtr.keymapper.server.InputService.<clinit>(InputService.java:201)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
03-26 15:44:24.648  2805  2805 E AndroidRuntime: Error reporting crash
03-26 15:44:24.648  2805  2805 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:550)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:348)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at android.os.ServiceManager.rawGetService(ServiceManager.java:306)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:134)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:4558)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:4555)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:43)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at android.app.ActivityManager.getService(ActivityManager.java:4546)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:158)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-26 15:44:24.648  2805  2805 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
03-26 15:44:24.648  2805  2805 I Process : Sending signal. PID: 2805 SIG: 9
03-26 15:45:00.003   381   381 D KeyguardClockSwitch: Updating clock: 3:45
```
XtMapper-release-v1.4
waydroid 1.4.0
android 11
LineageOS 18.1-20230318-VANILLA-waydroid_x86_64

**Comment by Xtr126** [comment]
Thanks for reporting, I did not encounter this library not found error as I was using arch linux, only Ubuntu has this issue. Tested on Ubuntu today and found a fix https://github.com/Xtr126/XtMapper/commit/df9af2a041944c074032819fdec434ec556df5de #35. Will be fixed in next release.
